### ISSUE TITLE
Bad links in README.md

### ISSUE THREAD

**Issue by varkoly** [trento-project/wanda#126]
There are 2 links for docker:  [docker-compose file](https://github.com/trento-project/wanda/blob/main/docker-compose.yaml) and [docker-compose.checks.yaml](https://github.com/trento-project/wanda/blob/main/docker-compose.checks.yaml). Neither of them works.

**Comment by gereonvey** [comment]
I was wondering why this works for me, until I discovered that if you read the README.md as rendered at https://www.trento-project.io/wanda/readme.html, the links are actually broken.
